# Generated by Django 2.2.7 on 2019-12-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='feedback',
            name='phoneno',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
