# Generated by Django 2.2.7 on 2019-12-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191220_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
