# Generated by Django 2.2.7 on 2019-12-20 13:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bullying', 'Bullying'), ('Stalking', 'Stalking'), ('Grooming', 'Grooming'), ('Sexting', 'Sexting'), ('Drug', 'Drug')], max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 12, 20, 19, 11, 49, 407453))),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, default='forum/default.png', upload_to='forum/')),
                ('social_media', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
