# Generated by Django 2.2.7 on 2019-12-20 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 19, 40, 11, 302837)),
        ),
    ]
