# Generated by Django 2.2.7 on 2019-12-20 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20191221_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 1, 49, 40, 3999)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
